# Ingresso Impresso: single entry point for Rust + WebAssembly + web.
# Run `just` (or `just check`) before every commit: it is exactly what CI runs.

set shell := ["bash", "-euo", "pipefail", "-c"]
# DATABASE_URL etc. for sqlx macros and tests (see .env.example).
set dotenv-load

wasm_target := "wasm32-unknown-unknown"
wasm_out := "packages/ticket-core-wasm/pkg"

# Everything CI runs, in order.
default: check

check: fmt-check clippy test-rust generated-check wasm js-install js-check

# --- Rust -------------------------------------------------------------------

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all -- --check

clippy:
    cargo clippy --locked --workspace --all-targets --all-features -- -D warnings
    cargo clippy --locked -p ticket-wasm --target {{wasm_target}} -- -D warnings

# Also regenerates the ts-rs bindings (feature `ts`); deleting them first exposes orphans
# (a removed or renamed DTO) as a diff in `generated-check`. Needs DATABASE_URL (sqlx tests).
test-rust:
    rm -f packages/ticket-core-wasm/src/generated/*.ts packages/api-types/src/generated/*.ts
    cargo test --locked --workspace --all-features
    just api-types-index

# Re-exports every generated API type from packages/api-types/src/index.ts.
api-types-index:
    cd packages/api-types/src && { \
        echo '// Generated by `just api-types-index` from src/generated (ts-rs). Do not edit.'; \
        for file in generated/*.ts; do echo "export type * from \"./${file%.ts}\";"; done; \
    } > index.ts

# Refreshes the offline query cache (.sqlx) used by Docker and CI builds. Needs DATABASE_URL.
db-prepare:
    cargo sqlx prepare --workspace -- --all-targets --all-features

# Applies migrations to DATABASE_URL (the server also does it at startup).
db-migrate:
    sqlx migrate run --source crates/server/migrations

# Regenerates the shared test vectors. Only for an intentional format/spec change: review the diff.
vectors:
    cargo run --locked -q -p ii-cli -- vectors generate --out testdata/vectors/ticket-v1.json

# Fails if generated files (TS bindings, vectors) are not committed up to date.
generated-check:
    cargo run --locked -q -p ii-cli -- vectors check --path testdata/vectors/ticket-v1.json
    git diff --exit-code -- packages/ticket-core-wasm/src/generated packages/api-types/src testdata/vectors .sqlx
    untracked="$(git ls-files --others --exclude-standard -- packages/ticket-core-wasm/src/generated packages/api-types/src .sqlx)"; \
        if [ -n "$untracked" ]; then echo "untracked generated files:"; echo "$untracked"; exit 1; fi

# --- WebAssembly ------------------------------------------------------------

# Builds ticket-wasm and generates the JS glue into packages/ticket-core-wasm/pkg.
wasm:
    cargo build --locked -p ticket-wasm --target {{wasm_target}} --profile release-wasm
    wasm-bindgen --target web --out-dir {{wasm_out}} --out-name ticket_core \
        target/{{wasm_target}}/release-wasm/ticket_wasm.wasm
    @ls -l {{wasm_out}}/ticket_core_bg.wasm | awk '{print "ticket_core_bg.wasm: " $5 " bytes"}'

# --- JavaScript / web ---------------------------------------------------------

js-install:
    pnpm install --frozen-lockfile

js-check:
    pnpm -r run typecheck
    pnpm -r run lint
    pnpm -r run test
    pnpm --filter @ingressoimpresso/web run build

# --- Local development --------------------------------------------------------

# Local Postgres for the API (phase 3 onwards).
db-up:
    docker compose -f deploy/compose.dev.yaml up -d

db-down:
    docker compose -f deploy/compose.dev.yaml down

web-dev:
    pnpm --filter @ingressoimpresso/web run dev

# Restore test of an encrypted backup into an EMPTY database (RESTORE_DATABASE_URL); monthly.
backup-restore-test dump identity:
    ./deploy/restore-test.sh {{dump}} {{identity}}

# Door end-to-end test (5 fake-camera phones): needs Postgres at DATABASE_URL, `just wasm` and the
# Playwright Chromium (`pnpm exec playwright install chromium` outside this dev container).
e2e:
    ./e2e/run.sh
