/**
 * Every user-facing text of the web app, in Brazilian Portuguese.
 *
 * Components never hard-code UI strings: they read them from here. There is no i18n framework on
 * purpose (national market only); centralizing keeps a future translation a mechanical change.
 */
export const texts = {
  meta: {
    title: "Ingresso Impresso",
    tagline: "Ingressos impressos à prova de cópia",
    description:
      "Ingressos impressos, numerados e com QR code à prova de cópia, com check-in na porta pelo celular, mesmo sem internet.",
  },
  brand: {
    name: "Ingresso Impresso",
    home: "Página inicial do Ingresso Impresso",
  },
  nav: {
    howItWorks: "Como funciona",
    features: "Recursos",
    pricing: "Preços",
    faq: "Dúvidas",
    templates: "Modelos",
    signIn: "Entrar",
    start: "Começar agora",
    panel: "Abrir o painel",
    menu: "Menu",
  },
  landing: {
    eyebrow: "Para quem vende ingresso na mão",
    headline: "Ingressos impressos com QR code que não dá para copiar",
    lead: "Crie, imprima e confira na porta pelo celular, mesmo sem internet. Feito para bandas, festas de escola, igrejas e pequenos produtores.",
    primaryCta: "Criar meu evento",
    secondaryCta: "Ver como funciona",
    trust: ["30 ingressos grátis para testar", "16 modelos prontos", "Sem mensalidade", "A partir de R$ 0,05 por ingresso"],
    templatesTitle: "Um modelo pronto para cada tipo de evento",
    templatesLead:
      "Escolha o modelo, troque as cores e pronto: o nome, a data e o local do evento entram sozinhos. Prefere a sua arte? Envie e posicione tudo arrastando.",
    templatesCta: "Montar meu ingresso",
    templateSamples: {
      show: { name: "Rock no Parque", venue: "Parque da Cidade" },
      party: { name: "Baile do Havaí", venue: "Clube Recreativo" },
      arraia: { name: "Arraiá da Escola São José", venue: "Quadra da escola" },
      graduation: { name: "Formatura Terceirão 2026", venue: "Espaço Villa Real" },
      church: { name: "Congresso de Jovens", venue: "Igreja Batista Central" },
      wedding: { name: "Jantar de Gala Beneficente", venue: "Salão Imperial" },
      theater: { name: "O Quebra-Nozes", venue: "Teatro Municipal" },
      sports: { name: "Copa do Bairro de Futsal", venue: "Ginásio Poliesportivo" },
      raffle: { name: "Rifa da Formatura", venue: "Colégio Estadual" },
      charity: { name: "Feijoada Solidária", venue: "Salão Paroquial" },
      kids: { name: "Festa da Primavera", venue: "Escola Pequeno Príncipe" },
      carnival: { name: "Bloco Sai da Frente", venue: "Praça da Matriz" },
      talk: { name: "Workshop de Fotografia", venue: "Coworking Centro" },
      cinema: { name: "Mostra de Curtas", venue: "Cine Clube" },
      newYear: { name: "Réveillon da Praia", venue: "Quiosque do Mar" },
      classic: { name: "Recital de Piano", venue: "Auditório da Escola de Música" },
    },
    audienceTitle: "Feito para quem organiza de verdade",
    audience: ["Bandas independentes", "Festas de escola", "Igrejas e quermesses", "Formaturas", "Teatro e dança", "Pequenos produtores"],
    mock: {
      event: "Show de Lançamento",
      venue: "Bar do Zé · 20 nov · 22h",
      number: "Nº 0042",
      admit: "PODE ENTRAR",
      seller: "Vendedor: João",
      synced: "Porta 1 · offline há 3 min",
    },
    featuresTitle: "Tudo o que o seu evento precisa, do papel à porta",
    featuresLead: "Do arquivo de impressão ao acerto com os vendedores, sem planilha e sem susto na entrada.",
    features: [
      {
        title: "QR assinado à prova de cópia",
        body: "Cada ingresso tem uma assinatura digital única. Ingresso falso não passa, e a cópia de um verdadeiro é barrada na segunda leitura.",
      },
      {
        title: "Pronto para imprimir",
        body: "A4 para imprimir em casa, PDF com sangria para a gráfica ou imagens para enviar pelo WhatsApp.",
      },
      {
        title: "Portaria sem internet",
        body: "Qualquer celular vira leitor. A decisão é na hora, sem esperar a rede, e os celulares se sincronizam quando o sinal volta.",
      },
      {
        title: "Blocos por vendedor",
        body: "Entregue faixas de números a cada vendedor e saiba quem vendeu, quem devolveu e quanto cada um precisa acertar.",
      },
      {
        title: "Cancelamento na hora",
        body: "Bloco perdido? Cancele a faixa e os números são barrados na porta.",
      },
      {
        title: "Relatório em tempo real",
        body: "Entradas, cópias barradas e o acerto por vendedor, com exportação para planilha.",
      },
      {
        title: "16 modelos prontos",
        body: "Shows, festas juninas, formaturas, igrejas, rifas e mais, em várias cores. O nome, a data e o local entram sozinhos.",
      },
      {
        title: "Editor visual",
        body: "Arraste textos, número e QR code, troque fontes e cores e veja na hora como vai sair na impressão.",
      },
      {
        title: "Rifas e sorteios",
        body: "Formato compacto com número grande e canhoto para nome e telefone: 12 por folha A4.",
      },
    ],
    stepsTitle: "Como funciona",
    stepsLead: "Do primeiro clique ao último convidado, em quatro passos.",
    steps: [
      { title: "Monte o ingresso", body: "Escolha um modelo para o seu tipo de evento ou envie a sua arte. A prévia mostra exatamente o que vai sair na impressão." },
      { title: "Crie e pague um lote", body: "Escolha quantos ingressos quer. Pague com Pix ou cartão e os ingressos ficam prontos na hora." },
      { title: "Imprima e distribua", body: "Baixe os arquivos, imprima em casa ou na gráfica e entregue os blocos aos vendedores." },
      { title: "Confira na porta", body: "Envie o link da portaria para a equipe. Cada celular lê os ingressos, com ou sem internet." },
    ],
    offlineTitle: "A porta não pode parar. Por isso ela não depende da internet.",
    offlineBody:
      "A portaria roda no navegador do celular e decide cada leitura na hora, com a mesma criptografia do servidor. Sem sinal, continua funcionando; quando a conexão volta, os celulares trocam as leituras e as cópias aparecem no relatório.",
    offlinePoints: ["Verde, vermelho ou amarelo em tela cheia, com som", "Lanterna para lugares escuros", "Vários celulares na mesma porta"],
    pricingTitle: "Centavos por ingresso. Sem mensalidade.",
    pricingLead: "Você paga uma vez por lote. Quanto mais ingressos, menor o preço de cada um. E os primeiros são por nossa conta.",
    pricingFree: (count: number) => `Seus primeiros ${count.toLocaleString("pt-BR")} ingressos são grátis`,
    pricingFreeBody: "Crie a conta, monte o ingresso, imprima e teste a portaria sem pagar nada.",
    pricingTier: (from: number, to: number) => `Do ${from.toLocaleString("pt-BR")}º ao ${to.toLocaleString("pt-BR")}º ingresso`,
    pricingPerTicket: "por ingresso",
    pricingMinimum: (amount: string) => `Valor mínimo por lote: ${amount}.`,
    pricingIncluded: ["Arquivos ilimitados do lote", "Portaria com celulares ilimitados", "Relatório e acerto por vendedor", "Pix ou cartão, pago com segurança pela Stripe"],
    pricingExample: (quantity: number, amount: string) => `Exemplo: ${quantity.toLocaleString("pt-BR")} ingressos saem por ${amount}.`,
    pricingUnavailable: "Os preços aparecem aqui assim que o servidor responder.",
    faqTitle: "Perguntas frequentes",
    faq: [
      {
        q: "Preciso de internet na porta?",
        a: "Não. Abra o link da portaria no celular no dia do evento, com internet, e ele continua lendo ingressos mesmo se o sinal cair.",
      },
      {
        q: "E se alguém tirar xerox do ingresso?",
        a: "A primeira leitura entra e as cópias são barradas. Se dois celulares estiverem sem internet ao mesmo tempo, a cópia aparece no relatório quando eles sincronizarem.",
      },
      {
        q: "Posso imprimir em casa?",
        a: "Sim. Geramos um A4 com marcas de corte para impressora comum, e também um PDF com sangria para gráfica.",
      },
      {
        q: "Como pago?",
        a: "Por lote, com Pix ou cartão, pela Stripe. O lote é liberado assim que o pagamento é confirmado.",
      },
      {
        q: "Preciso saber design?",
        a: "Não. Escolha um dos modelos prontos e o ingresso já sai com o nome, a data e o local do evento. Se quiser, troque cores, fontes e textos arrastando na tela.",
      },
      {
        q: "Dá para fazer rifa?",
        a: "Sim. O modelo de rifa tem número grande e canhoto para o nome e o telefone do comprador, e cabem 12 por folha A4.",
      },
      {
        q: "Funciona no iPhone?",
        a: "Sim. A portaria funciona no Safari do iPhone e no Chrome do Android, sem instalar nada.",
      },
    ],
    finalTitle: "Seu próximo evento merece uma portaria tranquila",
    finalBody: "Crie o evento em minutos e teste com ingressos grátis. Depois, centavos por ingresso.",
    footer: "Ingressos impressos, numerados e conferidos pelo celular.",
    footerRights: (year: number) => `© ${String(year)} Ingresso Impresso`,
  },
  footer: {
    tagline: "Ingressos numerados com QR à prova de cópia, impressos ou no celular, e portaria que funciona sem internet.",
    cta: "Criar meu evento",
    product: "Produto",
    howItWorks: "Como funciona",
    templates: "Modelos",
    pricing: "Preços",
    faq: "Dúvidas",
    news: "Novidades",
    legal: "Legal",
    terms: "Termos de Uso",
    privacy: "Política de Privacidade",
    refund: "Política de Reembolso",
    contact: "Contato",
    contactBody: "Dúvidas, suporte ou pedidos sobre seus dados:",
    rights: (year: number) => `© ${String(year)} Ingresso Impresso`,
    provider: (name: string, document: string) => `${name} · ${document}`,
    theme: "Tema",
  },
  legal: {
    updatedAt: (date: string) => `Atualizado em ${date}`,
    summaryTitle: "Resumo",
    summaryHint: "O resumo ajuda a ler; o que vale é o texto completo abaixo.",
    contents: "Nesta página",
    otherDocuments: "Outros documentos",
    questions: "Ficou alguma dúvida?",
    questionsBody: "Escreva para o nosso e-mail. Respondemos em até 5 dias.",
    print: "Imprimir ou salvar em PDF",
  },
  changelog: {
    title: "Novidades",
    subtitle: "Tudo o que mudou no Ingresso Impresso: recursos novos, melhorias, correções e segurança.",
    metaDescription: "O que há de novo no Ingresso Impresso: recursos, melhorias, correções e segurança.",
    all: "Todas",
    kinds: { new: "Novo", improvement: "Melhoria", fix: "Correção", security: "Segurança" },
    empty: "Nenhuma novidade publicada ainda.",
    emptyFiltered: "Nenhuma novidade deste tipo.",
    unavailable: "Não foi possível carregar as novidades agora.",
    open: "Novidades",
    unread: (count: number) => (count === 1 ? "1 novidade não lida" : `${String(count)} novidades não lidas`),
    seeAll: "Ver todas as novidades",
    latest: "Últimas novidades",
    newBadge: "Novo",
    cta: "Ainda não usa? Crie seu evento e teste com ingressos grátis.",
    ctaButton: "Criar meu evento",
    admin: {
      intro: "Publique aqui o que mudou. As notas aparecem em /novidades e no sininho do painel de todos os organizadores.",
      new: "Nova nota",
      edit: "Editar nota",
      kind: "Tipo",
      titleLabel: "Título",
      titlePlaceholder: "Ingressos no celular",
      body: "Texto",
      bodyHint: "Escreva para o organizador: o que mudou e como usar. Linhas em branco separam parágrafos.",
      published: "Publicada",
      publishedHint: "Desligada, a nota fica como rascunho, visível só para admins.",
      draft: "Rascunho",
      publishedAt: (date: string) => `Publicada em ${date}`,
      saved: "Nota salva.",
      deleted: "Nota excluída.",
      deleteTitle: "Excluir esta nota?",
      deleteBody: "Ela some de /novidades e do painel. Não dá para desfazer.",
      empty: "Nenhuma nota ainda. Publique a primeira novidade.",
    },
  },
  common: {
    save: "Salvar",
    saving: "Salvando…",
    saved: "Salvo",
    cancel: "Cancelar",
    close: "Fechar",
    confirm: "Confirmar",
    remove: "Remover",
    edit: "Editar",
    loading: "Carregando…",
    add: "Adicionar",
    back: "Voltar",
    retry: "Tentar de novo",
    skipToContent: "Pular para o conteúdo",
    currency: "R$",
    mm: "mm",
    pt: "pt",
    yes: "Sim",
    no: "Não",
    optional: "opcional",
    first: "Do nº",
    last: "Até o nº",
    range: (first: number, last: number) => `${String(first)} a ${String(last)}`,
    tickets: (count: number) => (count === 1 ? "1 ingresso" : `${count.toLocaleString("pt-BR")} ingressos`),
  },
  theme: {
    label: "Tema",
    options: { light: "Claro", dark: "Escuro", system: "Sistema" },
  },
  notFound: {
    title: "Página não encontrada",
    body: "O endereço pode estar errado, ou a página mudou de lugar.",
    home: "Página inicial",
    panel: "Meus eventos",
  },
  crash: {
    title: "Algo deu errado nesta página",
    body: "Tente de novo. Se o problema continuar, recarregue a página ou volte mais tarde.",
  },
  pwa: {
    install: "Instalar app",
    installTitle: "Instale o Ingresso Impresso",
    installBody: "Abra o painel direto da tela inicial, em tela cheia, como um aplicativo.",
    iosSteps: ["Toque em Compartilhar na barra do Safari.", "Escolha “Adicionar à Tela de Início”.", "Toque em Adicionar."],
    installed: "App instalado!",
    offlineTitle: "Você está sem internet",
    offlineBody: "O painel precisa de conexão para mostrar seus eventos. A portaria continua funcionando sem internet nos celulares já preparados.",
    offlineRetry: "Tentar de novo",
    offlineDoor: "Abrir a portaria",
    updateReady: "Nova versão disponível.",
    updateAction: "Atualizar",
  },
  login: {
    title: "Entrar",
    subtitle: "Sem senha. Entre com o Google ou receba um código no seu e-mail.",
    firstTime: "Primeira vez? A conta é criada na hora, com 30 ingressos grátis para testar.",
    google: "Continuar com Google",
    googleSigningIn: "Entrando com Google…",
    or: "ou com seu e-mail",
    emailLabel: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    sendCode: "Receber código por e-mail",
    sending: "Enviando…",
    codeTitle: "Confira seu e-mail",
    codeSentTo: (email: string) => `Enviamos um código de 6 dígitos para ${email}.`,
    codeLabel: "Código de 6 dígitos",
    codeDigit: (position: number) => `Dígito ${String(position)} do código`,
    verify: "Entrar",
    verifying: "Entrando…",
    otherEmail: "Usar outro e-mail",
    resend: "Reenviar código",
    resendIn: (seconds: number) => `Reenviar em ${String(seconds)} s`,
    resent: "Enviamos um novo código.",
    spamHint: "Não chegou? Olhe a caixa de spam ou promoções.",
    quotaTitle: "Os códigos por e-mail acabaram por hoje",
    quotaBody: "Entre com sua conta Google: é instantâneo e não depende de e-mail.",
    termsBefore: "Ao continuar, você concorda com os ",
    termsLink: "Termos de Uso",
    termsMiddle: " e a ",
    privacyLink: "Política de Privacidade",
    termsAfter: ".",
    asideTitle: "Do papel à porta, sem dor de cabeça.",
    asidePoints: [
      "QR code assinado, à prova de cópia",
      "Impresso em casa, na gráfica ou no celular",
      "Portaria pelo celular, mesmo sem internet",
    ],
  },
  panel: {
    title: "Meus eventos",
    subtitle: "Crie um evento para montar o ingresso, gerar os lotes e preparar a portaria.",
    signOut: "Sair",
    account: "Conta",
    accountPage: "Minha conta",
    admin: "Administrador",
    events: "Eventos",
    newEvent: "Novo evento",
    newEventDescription: "Você pode mudar tudo isso depois.",
    editEvent: "Editar evento",
    emptyTitle: "Nenhum evento ainda",
    empty: "Crie o primeiro evento para montar o ingresso e gerar os lotes.",
    eventName: "Nome do evento",
    eventNamePlaceholder: "Show de Lançamento",
    venue: "Local",
    venuePlaceholder: "Bar do Zé",
    startsAt: "Início",
    endsAt: "Fim",
    price: "Preço do ingresso",
    priceHint: "Usado no acerto com os vendedores. Deixe em branco se for gratuito.",
    pricePlaceholder: "30,00",
    priceInvalid: "Valor inválido. Use só números, como 30 ou 30,50.",
    timeZoneHint: (zone: string) => `Horários no fuso deste aparelho (${zone.replace(/_/g, " ")}).`,
    eventTimeZoneHint: (minutes: number) => {
      const hours = Math.abs(minutes) / 60;
      const label = Number.isInteger(hours) ? String(hours) : hours.toFixed(1).replace(".", ",");
      return `Horários no horário local do evento (UTC${minutes < 0 ? "−" : "+"}${label}).`;
    },
    create: "Criar evento",
    creating: "Criando…",
    created: "Evento criado.",
    updated: "Evento atualizado.",
    upcoming: "Próximo",
    today: "Hoje",
    happening: "Acontecendo",
    past: "Encerrado",
    noVenue: "Local a definir",
    unreachableTitle: "Não foi possível carregar o painel",
    activeFilter: "Em andamento",
    noActiveTitle: "Nenhum evento em andamento",
    archivedFilter: (count: number) => `Arquivados (${count.toLocaleString("pt-BR")})`,
    results: "Resultados",
    news: "Novidades",
    suspended: "Sua conta está suspensa: dá para ver tudo, mas não para criar lotes, gerar arquivos ou enviar ingressos.",
    suspendedAction: "Ver detalhes",
    support: "Suporte",
  },
  event: {
    backToEvents: "Eventos",
    notFoundTitle: "Evento não encontrado",
    notFound: "Ele pode ter sido removido, ou o link é de outra conta.",
    priceLabel: (price: string) => `${price} o ingresso`,
    actions: {
      menu: "Mais ações",
      duplicate: "Duplicar evento",
      duplicated: "Evento duplicado com o ingresso e os vendedores. Ajuste a data e o nome.",
      archive: "Arquivar evento",
      archiveTitle: "Arquivar o evento?",
      archiveBody: "Ele sai da lista principal e não aceita novos lotes. Os arquivos e a portaria continuam funcionando.",
      archived: "Evento arquivado.",
      reopen: "Reabrir evento",
      reopened: "Evento reaberto.",
      delete: "Excluir evento",
      deleteTitle: "Excluir o evento?",
      deleteBody: "Só eventos sem lotes podem ser excluídos, e isso não pode ser desfeito. Eventos com lotes pagos podem ser arquivados.",
      deleted: "Evento excluído.",
      archivedBadge: "Arquivado",
      archivedNote: "Este evento está arquivado: reabra para criar lotes.",
    },
    tabs: {
      overview: "Visão geral",
      design: "Ingresso",
      batches: "Lotes",
      sellers: "Vendedores",
      voids: "Cancelamentos",
      files: "Arquivos",
      door: "Portaria",
      report: "Relatório",
    },
    overview: {
      title: "Passo a passo",
      subtitle: "Siga a ordem abaixo para ter o evento pronto para a porta.",
      progress: (done: number, total: number) => `${String(done)} de ${String(total)} concluídos`,
      go: "Abrir",
      done: "Feito",
      steps: {
        design: { title: "Monte o ingresso", body: "Escolha um modelo pronto ou envie a sua arte e ajuste os textos." },
        batches: { title: "Crie e pague um lote", body: "Os arquivos só podem ser gerados para lotes pagos." },
        sellers: { title: "Distribua entre vendedores", body: "Opcional: entregue faixas de números e acompanhe o acerto." },
        files: { title: "Gere os arquivos", body: "A4 para casa, PDF para gráfica ou imagens para WhatsApp." },
        door: { title: "Prepare a portaria", body: "Crie um link e registre os celulares que vão ler os ingressos." },
      },
      stats: {
        paid: "Ingressos pagos",
        sellers: "Vendedores",
        entries: "Entradas",
        devices: "Celulares na porta",
      },
    },
    design: {
      intro:
        "Comece por um modelo ou monte do zero: arraste os elementos, edite os textos e veja o resultado na hora. A prévia de impressão mostra a folha A4 com ingressos de AMOSTRA, exatamente como sai.",
      toolbar: {
        templates: "Modelos",
        addText: "Texto",
        undo: "Desfazer",
        redo: "Refazer",
        printPreview: "Prévia de impressão",
      },
      canvas: {
        label: "Ingresso (área de edição)",
        hint: "Arraste para mover e puxe o canto para redimensionar. Setas movem 0,5 mm (com Shift, 5 mm).",
        hiddenText: "Campo vazio: não é impresso",
        textElement: (value: string) => `Texto: ${value}`,
        numberElement: "Número do ingresso",
        qrElement: "QR code",
      },
      startTitle: "Comece por um modelo",
      startBody: "16 modelos prontos para shows, festas juninas, formaturas, igrejas, rifas e mais, já com os dados do seu evento.",
      startAction: "Ver modelos",
      elements: "Elementos",
      elementsHint: "Clique num elemento aqui ou no ingresso para editar.",
      texts: "Textos",
      noTexts: "Nenhum texto. Adicione o nome do evento, a data e o local.",
      newText: "{evento}",
      selected: "Elemento selecionado",
      deselect: "Fechar edição",
      text: "Texto",
      textHint:
        "Campos entre chaves trocam pelos dados do evento. Um texto com campo vazio (sem local, sem preço) não sai na impressão.",
      insertField: "Inserir campo",
      fields: {
        evento: "Evento",
        data: "Data",
        data_extenso: "Data por extenso",
        semana: "Dia da semana",
        dia: "Dia",
        mes: "Mês",
        mes_curto: "Mês curto",
        ano: "Ano",
        hora: "Hora",
        local: "Local",
        preco: "Preço",
      },
      lines: "Linhas",
      linesOption: (lines: number) => (lines === 1 ? "1 linha (encolhe para caber)" : `Até ${String(lines)} linhas`),
      bold: "Negrito",
      boldUnavailable: "Esta fonte não tem negrito.",
      uppercase: "Maiúsculas",
      letterSpacing: "Espaçamento (em)",
      position: "Posição e tamanho",
      duplicate: "Duplicar",
      remove: "Excluir",
      forward: "Trazer para frente",
      backward: "Enviar para trás",
      removedText: "Texto excluído.",
      issuesTitle: "Ajuste antes de salvar",
      issues: {
        bodySize: (width: readonly [number, number], height: readonly [number, number]) =>
          `O ingresso precisa ter de ${String(width[0])} a ${String(width[1])} mm de largura e de ${String(height[0])} a ${String(height[1])} mm de altura.`,
        a4: "Com o canhoto, o ingresso não cabe numa folha A4.",
        color: "Use uma cor no formato #rrggbb.",
        numberOutside: "O número precisa ficar inteiro dentro do ingresso.",
        numberSize: (range: readonly [number, number]) => `O tamanho do número vai de ${String(range[0])} a ${String(range[1])} pt.`,
        digits: (max: number) => `O número pode ter de 1 a ${String(max)} dígitos.`,
        prefix: (max: number) => `O prefixo tem no máximo ${String(max)} caracteres.`,
        qrSmall: (min: number) => `O QR code precisa ter pelo menos ${String(min)} mm para ser lido rápido.`,
        qrOutside: "O QR code precisa ficar inteiro dentro do ingresso.",
        stubWidth: (range: readonly [number, number]) => `O canhoto vai de ${String(range[0])} a ${String(range[1])} mm de largura.`,
        stubFields: (fields: number, chars: number) => `O canhoto aceita até ${String(fields)} campos de até ${String(chars)} caracteres.`,
        stubTooShort: (height: number) =>
          `Com esses campos no canhoto, o ingresso precisa ter pelo menos ${height.toLocaleString("pt-BR")} mm de altura.`,
        tooManyTexts: (max: number) => `O ingresso aceita até ${String(max)} textos.`,
        textTooLong: (index: number, max: number) => `O texto ${String(index)} passa de ${String(max)} caracteres.`,
        textOutside: (index: number) => `O texto ${String(index)} precisa ficar inteiro dentro do ingresso.`,
        textStyle: (index: number) => `O texto ${String(index)} tem tamanho, linhas ou espaçamento fora do permitido.`,
      },
      art: "Arte",
      artDrop: "Arraste a arte aqui ou clique para escolher",
      artFormats: "PNG ou JPEG, até 20 MB",
      artUploading: "Enviando a arte…",
      artReplace: "Trocar arte",
      artHint: (widthMm: number, heightMm: number) =>
        `Tamanho ideal: ${String(widthMm + 6)} × ${String(heightMm + 6)} mm (o ingresso + 3 mm de sangria em cada lado).`,
      artDpi: (dpi: number) => `${String(dpi)} dpi no tamanho final`,
      artLowDpi: "Abaixo de 300 dpi a impressão pode sair borrada.",
      artGoodDpi: "Boa resolução para impressão.",
      noArt: "Sem arte: o ingresso usa a cor de fundo.",
      removeArt: "Remover arte",
      size: "Tamanho do ingresso",
      sizeHint: "Sem contar o canhoto.",
      width: "Largura (mm)",
      height: "Altura (mm)",
      background: "Cor de fundo",
      number: "Número",
      numberHint: "Posição e estilo do número impresso.",
      x: "Esquerda (mm)",
      y: "Topo (mm)",
      boxWidth: "Largura da caixa (mm)",
      boxHeight: "Altura da caixa (mm)",
      font: "Fonte",
      fonts: {
        sans: "Lato (moderna)",
        display: "Bebas Neue (condensada)",
        condensed: "Anton (impacto)",
        serif: "Abril Fatface (clássica)",
        script: "Great Vibes (cursiva elegante)",
        casual: "Pacifico (divertida)",
        slab: "Alfa Slab One (serifa forte)",
        mono: "Space Mono (máquina de escrever)",
      },
      fontSize: "Tamanho (pt)",
      color: "Cor",
      align: "Alinhamento",
      aligns: { left: "Esquerda", center: "Centro", right: "Direita" },
      prefix: "Prefixo",
      digits: "Dígitos",
      qr: "QR code",
      qrHint: "Fica sempre sobre fundo branco. Mínimo de 22 mm para a leitura ser rápida.",
      qrSize: "Tamanho (mm)",
      stub: "Canhoto",
      stubHint: "Parte destacável que fica com o vendedor.",
      hasStub: "Com canhoto",
      stubSide: "Lado",
      sides: { left: "Esquerda", right: "Direita" },
      stubWidth: "Largura do canhoto (mm)",
      stubFields: "Campos do canhoto",
      stubFieldsHint: "Um por linha. Cada campo pede cerca de 8 mm de altura do ingresso.",
      defaultStubFields: ["Nome", "Telefone"],
      leaveConfirmTitle: "Sair sem salvar o ingresso?",
      leaveConfirmBody: "As mudanças no ingresso ainda não foram salvas e serão perdidas.",
      leaveConfirm: "Sair sem salvar",
      previewTitle: "Prévia de impressão",
      previewDescription: "A primeira folha A4 com ingressos de AMOSTRA (QR inválido), exatamente como o arquivo sai.",
      previewEmpty: "Gere a prévia para ver a folha A4 com ingressos de amostra.",
      preview: "Gerar prévia",
      previewing: "Gerando prévia…",
      previewAlt: "Prévia da folha A4 com ingressos de amostra",
      saved: (version: number) => `Versão ${String(version)} salva`,
      savedToast: (version: number) => `Ingresso salvo (versão ${String(version)}).`,
      unsaved: "Ainda não salvo",
      unsavedHint: "Enquanto não salvar, os arquivos usam o ingresso padrão.",
      dirty: "Alterações não salvas",
    },
    batches: {
      intro:
        "Cada lote é uma faixa de números. Depois do pagamento, os ingressos do lote podem ser gerados e impressos.",
      newBatch: "Novo lote",
      quantity: "Quantidade de ingressos",
      presets: [50, 100, 200, 500, 1000],
      numbering: (first: number, last: number) => `Numeração: ${String(first)} a ${String(last)}`,
      total: "Total do lote",
      perTicket: (amount: string) => `${amount} por ingresso, em média`,
      minimumApplied: "Valor mínimo por lote",
      priceTable: "Ver tabela de preços",
      tier: (from: number, to: number, unit: string) => `${from.toLocaleString("pt-BR")}º a ${to.toLocaleString("pt-BR")}º: ${unit} cada`,
      create: "Criar lote",
      creating: "Criando…",
      createdToast: "Lote criado. Agora é só pagar para liberar os ingressos.",
      createdToastManual: "Lote criado. Ele é liberado assim que o pagamento for confirmado.",
      createdFreeToast: "Lote grátis criado e liberado. Já dá para gerar os arquivos!",
      free: "Grátis",
      createFree: "Criar lote grátis",
      freeTitle: (count: number) => `Você tem ${count.toLocaleString("pt-BR")} ingressos grátis para testar`,
      freeBody: "Eles saem do seu próximo lote, em qualquer evento. Imprima, leia na portaria e veja tudo funcionando antes de pagar.",
      freeInBatch: (count: number) => `${count.toLocaleString("pt-BR")} ingressos grátis neste lote`,
      emptyTitle: "Nenhum lote ainda",
      empty: "Crie o primeiro lote para gerar os ingressos.",
      status: {
        awaiting_payment: "Aguardando pagamento",
        paid: "Pago",
        canceled: "Cancelado",
        refunded: "Estornado",
      },
      refundedNote: "Lote estornado: os números ficam cancelados na porta e não voltam a ser usados.",
      pendingState: { open: "Pagamento em andamento", processing: "Confirmando Pix" },
      moreActions: "Mais ações",
      paidVia: { stripe: "Pago online", admin: "Pago (confirmado pelo admin)", free: "Grátis (boas-vindas)" },
      pay: (amount: string) => `Pagar ${amount}`,
      redirecting: "Abrindo pagamento…",
      continuePayment: "Continuar pagamento",
      checkPayment: "Já paguei",
      checking: "Verificando…",
      markPaid: "Marcar como pago",
      cancelBatch: "Cancelar lote",
      cancelConfirmTitle: "Cancelar este lote?",
      cancelConfirmBody:
        "Nenhum ingresso deste lote poderá ser gerado. Se ele for o último lote, os números voltam a ficar livres para o próximo. Um pagamento aberto é encerrado.",
      cancelConfirm: "Cancelar lote",
      canceledToast: "Lote cancelado.",
      markPaidConfirmTitle: "Marcar como pago?",
      markPaidConfirmBody: "Use só para pagamentos feitos fora do site. Os ingressos do lote passam a poder ser gerados.",
      paymentDisabled: "Pagamento online indisponível no momento. Fale com o suporte para liberar o lote.",
      paymentSuccess: "Pagamento confirmado! Os ingressos do lote já podem ser gerados.",
      paymentProcessing: "Recebemos seu retorno. Assim que a Stripe confirmar o pagamento, o lote é liberado (Pix pode levar alguns instantes).",
      pixProcessing: "Pix recebido pela Stripe e aguardando confirmação do banco. O lote é liberado sozinho assim que confirmar.",
      paymentNotConfirmed: "Ainda não recebemos a confirmação",
      paymentCanceled: "Pagamento não concluído. Você pode tentar de novo quando quiser.",
      secure: "Pagamento seguro pela Stripe, com Pix ou cartão.",
      legalBefore: "Ao pagar, você concorda com os ",
      legalTerms: "Termos de Uso",
      legalMiddle: " e a ",
      legalRefund: "Política de Reembolso",
      legalAfter: " (arrependimento em até 7 dias).",
      goToFiles: "Gerar arquivos",
    },
    sellers: {
      intro: "Cadastre quem vende e entregue a cada um uma faixa de números. O relatório mostra o acerto de cada vendedor.",
      newSeller: "Novo vendedor",
      name: "Nome",
      namePlaceholder: "João",
      phone: "Telefone",
      phonePlaceholder: "(11) 98888-7777",
      create: "Cadastrar",
      createdToast: "Vendedor cadastrado.",
      emptyTitle: "Nenhum vendedor ainda",
      empty: "Vendedores são opcionais: use quando os ingressos forem vendidos por várias pessoas.",
      noRanges: "Nenhuma faixa entregue",
      ranges: "Faixas",
      assign: "Entregar faixa",
      assignTitle: (name: string) => `Entregar faixa para ${name}`,
      assignedToast: "Faixa entregue.",
      removeRange: (range: string) => `Remover a faixa ${range}`,
      removeConfirmTitle: (name: string) => `Remover ${name}?`,
      removeConfirmBody: "As faixas entregues a esse vendedor voltam a ficar sem vendedor.",
      removedToast: "Vendedor removido.",
      removeRangeConfirmTitle: (range: string) => `Tirar a faixa ${range} deste vendedor?`,
      removeRangeConfirmBody: "Os números continuam válidos, mas deixam de contar no acerto deste vendedor.",
      rangeRemovedToast: "Faixa removida do vendedor.",
      ticketsCount: (count: number) => (count === 1 ? "1 ingresso" : `${count.toLocaleString("pt-BR")} ingressos`),
    },
    voids: {
      intro:
        "Cancele faixas devolvidas, perdidas ou que não devem entrar. Elas são bloqueadas na porta e não aparecem nos arquivos.",
      newVoid: "Cancelar uma faixa",
      reason: "Motivo",
      reasons: { unsold: "Devolvido (não vendido)", lost: "Perdido ou roubado", revoked: "Outro motivo" },
      note: "Observação",
      notePlaceholder: "Bloco 3 esquecido no ônibus",
      create: "Cancelar faixa",
      createConfirmTitle: (range: string) => `Cancelar os números ${range}?`,
      createConfirmBody: "Esses ingressos serão barrados na porta. Dá para desfazer depois.",
      createdToast: "Faixa cancelada.",
      emptyTitle: "Nenhum cancelamento",
      empty: "Quando um bloco for devolvido ou perdido, cancele a faixa aqui.",
      undo: "Desfazer",
      undone: "Desfeito",
      undoneToast: "Cancelamento desfeito.",
    },
    files: {
      intro:
        "Gere os arquivos dos ingressos pagos. Ingressos cancelados não entram. Cada arquivo leva alguns segundos (as imagens do WhatsApp, um pouco mais).",
      newFile: "Novo arquivo",
      kind: "Tipo de arquivo",
      kinds: {
        home: "A4 para imprimir em casa",
        print: "PDF para gráfica (com sangria)",
        control: "Folha de controle por vendedor",
        whatsapp: "Imagens para WhatsApp (ZIP)",
      },
      kindHints: {
        home: "Vários ingressos por folha, com marcas de corte.",
        print: "Um ingresso por página, no tamanho final + 3 mm.",
        control: "Lista de números para anotar comprador e pagamento.",
        whatsapp: "Uma imagem por ingresso, em pastas por vendedor.",
      },
      scope: "Quais ingressos",
      scopeAll: "Todos os pagos",
      scopeBatch: (first: number, last: number) => `Lote ${String(first)}–${String(last)}`,
      scopeSeller: (name: string) => `Vendedor: ${name}`,
      cropMarks: "Marcas de corte",
      cropMarksHint: "Algumas gráficas preferem sem.",
      generate: "Gerar arquivo",
      generating: "Enviando…",
      queuedToast: "Arquivo na fila. Ele aparece abaixo quando ficar pronto.",
      noPaidTitle: "Nenhum lote pago",
      noPaid: "Pague um lote para poder gerar os arquivos dos ingressos.",
      goToBatches: "Ir para os lotes",
      history: "Arquivos gerados",
      emptyTitle: "Nenhum arquivo gerado ainda",
      empty: "Os arquivos ficam disponíveis aqui para baixar.",
      status: {
        queued: "Na fila",
        running: "Gerando…",
        done: "Pronto",
        failed: "Falhou",
      },
      tickets: (count: number) => (count === 1 ? "1 ingresso" : `${count.toLocaleString("pt-BR")} ingressos`),
      download: "Baixar",
      whatsappWarning: "Envie cada imagem a um só comprador: cópias são barradas na porta.",
    },
    report: {
      intro:
        "Acerto por vendedor: ingressos pagos entregues, devoluções, perdas, vendidos declarados e o valor a acertar. Entradas e cópias vêm da portaria.",
      csv: "Baixar CSV",
      refresh: "Atualizar",
      generatedAt: (time: string) => `Atualizado às ${time}`,
      noPrice: "Evento sem preço: o valor a acertar fica em branco.",
      fileName: "relatorio-vendedores.csv",
      seller: "Vendedor",
      unassigned: "Sem vendedor",
      totals: "Total",
      amountDue: "A acertar",
      sellersTitle: "Acerto por vendedor",
      stats: {
        sold: "Vendidos",
        entries: "Entradas",
        blocked: "Cópias barradas",
        amountDue: "Total a acertar",
      },
      columns: {
        tickets: "Ingressos",
        unsold: "Devolvidos",
        lost: "Perdidos",
        revoked: "Outros cancel.",
        declaredSold: "Vendidos",
        entries: "Entradas",
        offlineDuplicates: "Duplicadas offline",
        blockedCopies: "Cópias barradas",
        voidEntries: "Entraram cancelados",
      },
      hints: {
        tickets: "Ingressos pagos entregues ao vendedor",
        unsold: "Cancelados como devolvidos sem vender",
        lost: "Cancelados como perdidos ou roubados",
        revoked: "Cancelados por outro motivo (contam como vendidos)",
        declaredSold: "Ingressos − devolvidos − perdidos",
        entries: "Ingressos que entraram",
        offlineDuplicates: "Cópias que entraram por celulares sem internet",
        blockedCopies: "Cópias barradas na porta",
        voidEntries: "Ingressos cancelados que entraram (o celular ainda não sabia do cancelamento)",
      },
      door: "Portaria",
      device: "Celular",
      noDevices: "Nenhum celular registrado.",
      rejected: (invalid: number, otherEvent: number) =>
        `QR falsos ou ilegíveis: ${String(invalid)} · ingressos de outro evento: ${String(otherEvent)}`,
      deviceColumns: {
        scans: "Leituras",
        firstEntries: "Entradas",
        offlineDuplicates: "Duplicadas offline",
        blockedCopies: "Cópias barradas",
        invalid: "Inválidos",
      },
    },
    door: {
      intro:
        "Crie um link para quem vai trabalhar na porta. Cada pessoa abre o link no celular, dá um nome ao aparelho e já pode ler os ingressos, mesmo sem internet.",
      entries: (count: number) => (count === 1 ? "1 ingresso já entrou." : `${String(count)} ingressos já entraram.`),
      entriesLabel: "Entradas",
      devicesOnline: "Celulares ativos",
      linksActive: "Links ativos",
      newLink: "Novo link de acesso",
      label: "Para quem é o link",
      defaultLabel: "Equipe da porta",
      create: "Criar link",
      createdTitle: (label: string) => `Link criado: ${label}`,
      createdHint:
        "Copie ou compartilhe agora: o link não aparece de novo. Quem tiver o link consegue registrar um celular; se ele vazar, revogue e crie outro.",
      qrLabel: "QR code do link da portaria",
      qrHint: "Aponte a câmera do celular para abrir a portaria.",
      copy: "Copiar link",
      copied: "Copiado!",
      copyFailed: "Não foi possível copiar. Selecione o link e copie à mão.",
      revokedToast: "Link revogado.",
      disconnectedToast: "Celular desconectado.",
      whatsapp: "Enviar pelo WhatsApp",
      whatsappMessage: "Link da portaria (abra no celular que vai ler os ingressos):",
      hide: "Fechar",
      links: "Links",
      noLinks: "Nenhum link ainda.",
      activeUntil: (when: string) => `Ativo até ${when}`,
      expired: "Expirado",
      revoked: "Revogado",
      revokeLink: "Revogar",
      revokeLinkConfirmTitle: (label: string) => `Revogar o link “${label}”?`,
      revokeLinkConfirmBody: "Ninguém mais consegue registrar um celular com ele. Os celulares já registrados continuam funcionando.",
      devices: "Celulares",
      noDevices: "Nenhum celular registrado.",
      scans: (count: number) => (count === 1 ? "1 leitura" : `${String(count)} leituras`),
      lastSeen: (when: string) => `último contato ${when}`,
      neverSeen: "sem contato",
      online: "online",
      disconnected: "desconectado",
      disconnect: "Desconectar",
      disconnectConfirmTitle: (name: string) => `Desconectar “${name}”?`,
      disconnectConfirmBody: "Esse celular para de ler ingressos na próxima sincronização.",
    },
  },
  portaria: {
    title: "Portaria",
    loading: "Abrindo a portaria…",
    noAccess: "Abra o link de acesso que o organizador enviou para você.",
    registerTitle: "Registrar este celular",
    registerIntro: "Dê um nome a este celular. Ele aparece quando um ingresso já entrou por aqui.",
    deviceName: "Nome do celular",
    deviceNamePlaceholder: "Porta 1 - João",
    register: "Registrar",
    registering: "Registrando…",
    switchTitle: (deviceName: string) => `Este celular já está registrado como “${deviceName}”.`,
    keepDevice: "Continuar assim",
    useNewLink: "Usar o novo link",
    switchBlocked: "Há leituras não sincronizadas: conecte-se à internet e espere sincronizar antes de trocar de link.",
    revoked: "O acesso deste celular foi encerrado pelo organizador (ou o evento acabou).",
    forget: "Apagar os dados deste celular",
    forgetConfirm: "Apagar os dados da portaria deste celular?",
    start: "Começar a ler",
    stop: "Pausar",
    torchOn: "Acender lanterna",
    torchOff: "Apagar lanterna",
    entries: (count: number) => (count === 1 ? "1 entrada" : `${String(count)} entradas`),
    syncedAgo: (seconds: number) => (seconds < 5 ? "sincronizado agora" : `sincronizado há ${String(seconds)} s`),
    offlineFor: (minutes: number) => (minutes < 1 ? "sem sinal" : `sem sinal há ${String(minutes)} min`),
    neverSynced: "ainda não sincronizou",
    pending: (count: number) => (count === 1 ? "1 leitura não sincronizada" : `${String(count)} leituras não sincronizadas`),
    oneLineOffline: "Sem sinal: use um celular só por fila, senão cópias podem entrar por celulares diferentes.",
    checking: "Conferindo…",
    tapToContinue: "Toque para continuar",
    scanHint: "Aponte para o QR code do ingresso",
    device: "Celular",
    cameraError: "Não foi possível abrir a câmera. Libere o acesso à câmera nas configurações do navegador.",
    storageError: "Não foi possível salvar a leitura neste celular. Libere espaço e recarregue a página.",
    readiness: {
      title: "Pronto para ficar sem internet?",
      progress: (done: number, total: number) => `${String(done)} de ${String(total)}`,
      app: "App salvo para abrir sem internet",
      data: (time: string) => `Dados do evento atualizados às ${time}`,
      noData: "Dados do evento ainda não baixados",
      camera: "Câmera liberada",
      storage: "Armazenamento garantido",
      testScan: "Leitura de teste feita (leia qualquer QR, como o de um ingresso de amostra)",
      hint: "Abra este link no dia do evento, com internet, e deixe a tela aberta.",
    },
    result: {
      admit: "PODE ENTRAR",
      alreadyEntered: "JÁ ENTROU",
      alreadyEnteredAt: (time: string, device: string) => `às ${time} por ${device}`,
      voided: "INGRESSO CANCELADO",
      otherEvent: "INGRESSO DE OUTRO EVENTO",
      invalid: "INGRESSO INVÁLIDO",
      error: "ERRO NA LEITURA",
      voidReasons: { unsold: "devolvido sem vender", lost: "perdido ou roubado", revoked: "cancelado pelo organizador" },
      invalidReasons: {
        malformed: "QR ilegível ou que não é nosso",
        unknown_key: "assinatura desconhecida",
        revoked_key: "chave revogada",
        bad_signature: "falsificado",
      },
      seller: (name: string) => `Vendedor: ${name}`,
      number: (label: string) => `Nº ${label}`,
    },
  },
  account: {
    title: "Minha conta",
    subtitle: "Sua organização, os ingressos grátis e quanto custa cada lote.",
    organization: "Organização",
    organizationHint: "Como a sua banda, escola ou igreja aparece no Ingresso Impresso.",
    organizationName: "Nome da organização",
    saved: "Nome atualizado.",
    usage: "Uso",
    events: "Eventos",
    paidTickets: "Ingressos emitidos",
    free: "Ingressos grátis",
    freeLeft: (left: number) => (left === 1 ? "1 ingresso grátis disponível" : `${left.toLocaleString("pt-BR")} ingressos grátis disponíveis`),
    freeOf: (used: number, total: number) => `${used.toLocaleString("pt-BR")} de ${total.toLocaleString("pt-BR")} usados`,
    freeHint: "Saem automaticamente dos seus próximos lotes, em qualquer evento.",
    pricing: "Preços",
    pricingHint: "Você paga só pelos ingressos que gerar, por lote. Sem mensalidade.",
    tier: (from: number, to: number) => `Do ${from.toLocaleString("pt-BR")}º ao ${to.toLocaleString("pt-BR")}º ingresso`,
    perTicket: (amount: string) => `${amount} cada`,
    minimum: (amount: string) => `Lote mínimo de ${amount}.`,
    examples: "Exemplos",
    example: (quantity: number) => `${quantity.toLocaleString("pt-BR")} ingressos`,
    session: "Sessão",
    signedInAs: "Conectado como",
    googleLinked: "Login com Google ligado",
    googleNotLinked: "Entre uma vez com o Google para ligar sua conta Google a este e-mail.",
    suspendedTitle: "Conta suspensa",
    suspendedBody: (reason: string) =>
      `Sua conta pode ver tudo, mas não pode criar lotes, gerar arquivos nem enviar ingressos.${reason === "" ? "" : ` Motivo: ${reason}.`} Fale com o suporte para reativar.`,
    privacy: "Seus dados",
    privacyHint: "Você controla seus dados: baixe uma cópia ou exclua a conta quando quiser.",
    termsAccepted: (date: string) => `Termos de Uso e Política de Privacidade aceitos em ${date}.`,
    readTerms: "Termos de Uso",
    readPrivacy: "Política de Privacidade",
    export: "Baixar meus dados",
    exportHint: "Um arquivo JSON com a conta, os eventos, os lotes, os vendedores e os pagamentos.",
    exportFile: "ingresso-impresso-meus-dados.json",
    exported: "Download iniciado.",
    delete: "Excluir minha conta",
    deleteHint: "Apaga a conta e os dados dos eventos. Não dá para desfazer.",
    deleteTitle: "Excluir sua conta?",
    deleteBody:
      "Vamos apagar a organização, os eventos, as artes, os vendedores, os ingressos digitais e os dados da portaria. Lotes pagos ficam guardados, sem nada que identifique você, porque a lei exige guardar registros de pagamento por 5 anos. Os celulares da portaria são desconectados na hora.",
    deleteConfirmLabel: (email: string) => `Para confirmar, digite ${email}`,
    deleteConfirm: "Excluir conta",
    deleted: "Conta excluída. Obrigado por ter usado o Ingresso Impresso.",
  },
  admin: {
    title: "Administração",
    subtitle: "Todo o Ingresso Impresso num lugar: receita, organizações e lotes.",
    nav: "Admin",
    openPanel: "Painel de administração",
    forbiddenTitle: "Área restrita",
    forbidden: "Só administradores veem esta página.",
    tabs: {
      overview: "Visão geral",
      finance: "Financeiro",
      organizations: "Organizações",
      batches: "Lotes",
      changelog: "Novidades",
      audit: "Auditoria",
    },
    stats: {
      revenue: "Receita total",
      revenue30: "Receita em 30 dias",
      paidTickets: "Ingressos emitidos",
      freeLabel: "Ingressos grátis",
      freeHint: "Boas-vindas e cortesias",
      organizations: "Organizações",
      newOrganizations: (count: number) => `+${count.toLocaleString("pt-BR")} em 30 dias`,
      usersLabel: "Usuários",
      events: "Eventos",
      upcoming: (count: number) => `${count.toLocaleString("pt-BR")} por acontecer`,
      awaiting: "Lotes aguardando",
      processing: (count: number) => `${count.toLocaleString("pt-BR")} Pix em confirmação`,
      ticketShare: "Média por ingresso",
    },
    chartTitle: "Últimos 30 dias",
    chartDescription: "Receita dos lotes pagos por dia (horário de Brasília).",
    chartRevenue: "Receita",
    chartTickets: "Ingressos",
    chartSignups: "Cadastros",
    chartBar: (date: string, value: string) => `${date}: ${value}`,
    search: "Buscar por nome ou e-mail",
    finance: {
      periods: { 7: "7 dias", 30: "30 dias", 90: "90 dias", 365: "12 meses" } as Record<number, string>,
      revenue: "Receita do período",
      growth: (percent: string) => `${percent} vs. período anterior`,
      noPrevious: "Sem período anterior para comparar",
      net: "Líquido",
      netHint: (refunds: string) => `Estornos: ${refunds}`,
      batches: "Lotes cobrados",
      batchesHint: (tickets: string) => `${tickets} ingressos cobrados`,
      average: "Média por lote",
      pending: "A receber",
      pendingHint: (count: number) => (count === 1 ? "1 lote aguardando" : `${count.toLocaleString("pt-BR")} lotes aguardando`),
      chartTitle: "Receita no período",
      chartDaily: "Lotes pagos por dia (horário de Brasília).",
      chartMonthly: "Lotes pagos por mês (horário de Brasília).",
      methods: "Como os lotes foram pagos",
      methodNames: { stripe: "Online (Pix ou cartão)", admin: "Marcado pelo admin", free: "Grátis e cortesias" },
      methodLine: (batches: number, tickets: number) =>
        `${batches.toLocaleString("pt-BR")} ${batches === 1 ? "lote" : "lotes"} · ${tickets.toLocaleString("pt-BR")} ingressos`,
      top: "Quem mais comprou",
      topEmpty: "Nenhuma compra paga no período.",
      funnel: "Funil de novas contas",
      funnelHint: "Organizações criadas no período e até onde chegaram.",
      funnelSteps: ["Criaram a conta", "Criaram um evento", "Geraram ingressos", "Pagaram um lote"],
      noData: "Sem dados no período.",
    },
    organization: {
      back: "Organizações",
      owner: "Responsável",
      since: (date: string) => `Cliente desde ${date}`,
      suspendedBadge: "Suspensa",
      rename: "Renomear",
      renameTitle: "Renomear organização",
      renamed: "Organização renomeada.",
      suspend: "Suspender",
      suspendTitle: "Suspender esta conta?",
      suspendBody: "A conta continua vendo tudo, mas não cria lotes, não paga, não gera arquivos nem envia ingressos. A portaria dos eventos continua funcionando.",
      reason: "Motivo (aparece para o organizador)",
      reasonPlaceholder: "Pagamento contestado",
      suspended: "Conta suspensa.",
      unsuspend: "Reativar",
      unsuspended: "Conta reativada.",
      suspendedSince: (date: string) => `Suspensa desde ${date}`,
      members: "Pessoas",
      lastLogin: (date: string) => `Último acesso ${date}`,
      neverLoggedIn: "Ainda não entrou",
      google: "Google",
      sessions: (count: number) => (count === 1 ? "1 sessão aberta" : `${count.toLocaleString("pt-BR")} sessões abertas`),
      endSessions: "Encerrar sessões",
      endSessionsTitle: (email: string) => `Desconectar ${email} de todos os aparelhos?`,
      endSessionsBody: "A pessoa precisa entrar de novo em todos os navegadores e celulares.",
      sessionsEnded: "Sessões encerradas.",
      events: "Eventos",
      noEvents: "Nenhum evento ainda.",
      eventLine: (tickets: number, entries: number) =>
        `${tickets.toLocaleString("pt-BR")} ingressos · ${entries.toLocaleString("pt-BR")} entradas`,
      openEvent: "Abrir em modo suporte",
      history: "Histórico de ações dos admins",
      noHistory: "Nenhuma ação registrada.",
    },
    support: {
      banner: "Modo suporte: este evento é de outra organização. Tudo o que você mudar aqui fica registrado na auditoria.",
      backToAdmin: "Voltar ao admin",
    },
    audit: {
      intro: "Toda ação de um admin fora da própria conta fica registrada aqui.",
      search: "Buscar por admin, ação, organização ou evento",
      empty: "Nenhuma ação registrada.",
      actions: {
        support_write: "Alterou em modo suporte",
        batch_refund: "Estornou um lote",
        batch_price: "Mudou o preço de um lote",
        batch_mark_paid: "Marcou um lote como pago",
        organization_bonus: "Mudou a cortesia",
        organization_suspend: "Suspendeu a conta",
        organization_unsuspend: "Reativou a conta",
        organization_rename: "Renomeou a organização",
        user_sessions_revoke: "Encerrou as sessões de alguém",
        changelog_create: "Criou uma novidade",
        changelog_update: "Editou uma novidade",
        changelog_delete: "Excluiu uma novidade",
      } as Record<string, string>,
    },
    organizations: {
      empty: "Nenhuma organização encontrada.",
      owner: "Responsável",
      created: (date: string) => `Desde ${date}`,
      events: (count: number) => (count === 1 ? "1 evento" : `${count.toLocaleString("pt-BR")} eventos`),
      tickets: (count: number) => `${count.toLocaleString("pt-BR")} ingressos`,
      free: (used: number, total: number) => `Grátis: ${used.toLocaleString("pt-BR")} de ${total.toLocaleString("pt-BR")}`,
      lastBatch: (date: string) => `Último lote em ${date}`,
      noBatch: "Nenhum lote ainda",
      bonus: "Cortesia",
      bonusBadge: (count: number) => `+${count.toLocaleString("pt-BR")} de cortesia`,
      bonusTitle: (name: string) => `Cortesia para ${name}`,
      bonusDescription: (base: number) =>
        `Ingressos grátis além dos ${base.toLocaleString("pt-BR")} que toda organização recebe. O valor substitui a cortesia atual.`,
      bonusLabel: "Ingressos de cortesia",
      bonusSaved: "Cortesia atualizada.",
    },
    batches: {
      filters: { awaiting_payment: "Aguardando", paid: "Pagos", refunded: "Estornados", canceled: "Cancelados", all: "Todos" },
      empty: "Nenhum lote neste filtro.",
      numbers: (first: number, last: number) => `Nº ${first.toLocaleString("pt-BR")} a ${last.toLocaleString("pt-BR")}`,
      quantity: (count: number) => `${count.toLocaleString("pt-BR")} ingressos`,
      created: (date: string) => `Criado em ${date}`,
      paid: (date: string) => `Pago em ${date}`,
      openEvent: "Abrir evento",
      markedPaid: "Lote marcado como pago.",
      actions: "Ações do lote",
      changePrice: "Mudar o preço",
      priceTitle: "Novo preço do lote",
      priceDescription: (quantity: number) =>
        `${quantity.toLocaleString("pt-BR")} ingressos. Um pagamento aberto é encerrado; com preço zero, o lote é liberado na hora.`,
      priceLabel: "Valor do lote (R$)",
      priceSaved: "Preço atualizado.",
      refund: "Estornar",
      refundTitle: "Estornar este lote?",
      refundBody:
        "O lote vira \"Estornado\" e todos os números dele são cancelados na porta para sempre, inclusive os já impressos. Eles não voltam a ser usados em outros lotes.",
      refundOnStripe: "Devolver o dinheiro pela Stripe agora",
      refundOnStripeHint: "Desligado, só registra aqui (use se você já devolveu por fora).",
      refundNote: "Observação para o histórico",
      refundNotePlaceholder: "Pedido de arrependimento em 7 dias",
      refunded: "Lote estornado e números cancelados.",
      refundedAt: (date: string) => `Estornado em ${date}`,
    },
  },
  templates: {
    title: "Modelos de ingresso",
    subtitle: "Escolha um modelo pronto para o seu tipo de evento. Ele já vem com o nome, a data e o local do evento, e tudo pode ser editado depois.",
    open: "Modelos",
    all: "Todos",
    apply: "Usar este modelo",
    applying: "Aplicando o modelo…",
    applied: (name: string) => `Modelo "${name}" aplicado. Ajuste o que quiser e salve.`,
    replaceTitle: "Trocar o ingresso pelo modelo?",
    replaceBody: "A arte, as posições e os textos atuais serão substituídos. Nada é salvo até você clicar em Salvar.",
    replaceConfirm: "Usar o modelo",
    colors: "Cores",
    format: (width: number, height: number, stub: boolean) =>
      `${String(width)} × ${String(height)} mm${stub ? " + canhoto" : ""}`,
    categories: {
      music: "Música",
      party: "Festas",
      school: "Escola",
      church: "Igreja",
      formal: "Formal",
      culture: "Cultura",
      sports: "Esporte",
      charity: "Beneficente",
      business: "Palestras",
      kids: "Infantil",
    },
    items: {
      show: { name: "Show ao vivo", description: "Feixes de luz e letras fortes para bandas e shows." },
      party: { name: "Festa / balada", description: "Gradiente vibrante com luzes desfocadas." },
      arraia: { name: "Festa junina", description: "Bandeirinhas e xadrez para o arraiá da escola ou da igreja." },
      graduation: { name: "Formatura", description: "Convite vertical em azul e dourado, com moldura art déco." },
      church: { name: "Igreja / culto", description: "Luz suave e tipografia clássica para cultos, retiros e encontros." },
      wedding: { name: "Casamento / gala", description: "Ramos delicados e letra cursiva para jantares e celebrações." },
      theater: { name: "Teatro / dança", description: "Cortina, holofote e serifas para espetáculos e recitais." },
      sports: { name: "Esporte / campeonato", description: "Gramado, linhas do campo e letras de impacto." },
      raffle: { name: "Rifa / sorteio", description: "Compacto, com número grande e canhoto: 12 por folha A4." },
      charity: { name: "Beneficente", description: "Corações e cores quentes para ações solidárias." },
      kids: { name: "Festa infantil", description: "Balões e confete para festas e peças infantis." },
      carnival: { name: "Carnaval / bloco", description: "Confete e serpentina para blocos e bailes." },
      talk: { name: "Palestra / workshop", description: "Limpo e corporativo para cursos, congressos e palestras." },
      cinema: { name: "Cinema / sessão", description: "Película de filme para sessões e mostras." },
      newYear: { name: "Réveillon", description: "Fogos dourados para a virada do ano." },
      classic: { name: "Clássico", description: "Moldura simples que combina com qualquer evento." },
    },
    palettes: {
      neon: "Neon",
      fire: "Fogo",
      acid: "Ácido",
      classic: "Clássico",
      night: "Noite",
      sky: "Céu",
      lavender: "Lavanda",
      earth: "Terra",
      navy: "Azul e ouro",
      wine: "Vinho",
      black: "Preto",
      sage: "Sálvia",
      rose: "Rosé",
      ivory: "Marfim",
      red: "Vermelho",
      royal: "Azul royal",
      emerald: "Esmeralda",
      sunset: "Pôr do sol",
      tropical: "Tropical",
      field: "Gramado",
      court: "Quadra",
      volley: "Vôlei",
      yellow: "Amarelo",
      green: "Verde",
      blue: "Azul",
      coral: "Coral",
      teal: "Turquesa",
      graphite: "Grafite",
      rainbow: "Arco-íris",
      pastel: "Pastel",
      folia: "Folia",
      frevo: "Frevo",
      retro: "Retrô",
      gold: "Dourado",
      silver: "Prata",
    } as Record<string, string>,
    // Printed on the tickets; fields in braces are replaced by the event's details.
    content: {
      live: "Ao vivo",
      fromTime: "A partir das {hora}",
      invite: "Convite",
      graduation: "Formatura",
      atTime: "às {hora}",
      drawDate: "Sorteio: {data}",
      solidarity: "Ação solidária",
      contribution: "Contribuição: {preco}",
      startsAt: "Início às {hora}",
      session: "Sessão das {hora}",
      ticket: "Ingresso",
    },
  },
  errors: {
    generic: "Algo deu errado. Tente de novo.",
    network: "Sem conexão com o servidor. Verifique a internet e tente de novo.",
    unauthorized: "Sua sessão expirou. Entre de novo.",
    forbidden: "Você não tem permissão para isso.",
    not_found: "Não encontrado.",
    too_many_requests: "Muitas tentativas. Espere alguns minutos.",
    invalid_email: "E-mail inválido.",
    invalid_code: "Código errado ou expirado.",
    mail_unavailable: "Não conseguimos enviar o e-mail agora. Tente em alguns minutos.",
    invalid_name: "Nome inválido.",
    invalid_venue: "Local muito longo.",
    invalid_dates: "O fim precisa ser depois do início.",
    invalid_price: "Preço inválido.",
    invalid_design:
      "O ingresso tem medidas inválidas (veja o tamanho mínimo do QR, se tudo cabe no ingresso e se ele é alto o bastante para os campos do canhoto).",
    unsupported_art: "A arte precisa ser PNG ou JPEG.",
    art_too_large: "A arte é grande demais (máximo 10.000 px por lado).",
    payload_too_large: "Arquivo grande demais (máximo 20 MB).",
    unknown_art: "Arte não encontrada; envie de novo.",
    too_large_for_a4: "O ingresso (com canhoto) não cabe numa folha A4.",
    invalid_quantity: "Quantidade inválida (1 a 5.000).",
    batch_not_cancelable: "Só lotes não pagos podem ser cancelados.",
    batch_not_payable: "Este lote não está aguardando pagamento.",
    payment_pending: "Há um Pix deste lote aguardando confirmação. Espere a confirmação antes de mexer no lote.",
    batch_has_ranges: "Este lote tem faixas entregues a vendedores ou cancelamentos. Remova-os antes de cancelar o lote.",
    art_quota: "Você atingiu o limite de armazenamento de artes. Use arquivos menores ou reaproveite uma arte já enviada.",
    method_not_allowed: "Ação não permitida.",
    payments_unavailable: "Pagamento online indisponível no momento.",
    payment_provider_error: "Não conseguimos falar com a Stripe agora. Tente em alguns instantes.",
    seller_exists: "Já existe um vendedor com esse nome.",
    invalid_phone: "Telefone muito longo.",
    invalid_range: "Faixa inválida.",
    range_not_issued: "Todos os números da faixa precisam estar em um lote.",
    range_overlap: "Essa faixa se sobrepõe a outra já entregue.",
    invalid_note: "Observação muito longa.",
    already_undone: "Esse cancelamento já foi desfeito.",
    invalid_scope: "Seleção inválida.",
    export_not_ready: "O arquivo ainda não está pronto.",
    export_expired: "O arquivo expirou. Gere de novo.",
    no_tickets: "Não há ingressos pagos e não cancelados nessa seleção.",
    too_many_tickets: "Ingressos demais num arquivo só (máximo 10.000).",
    invalid_label: "Nome do link inválido (1 a 60 caracteres).",
    invalid_device_name: "Dê um nome ao celular (até 40 caracteres).",
    too_many_devices: "Este link já registrou celulares demais. Crie outro link.",
    invalid_scans: "Leituras inválidas.",
    scan_conflict: "Leitura em conflito com outro celular.",
    invalid_cursor: "Dados de sincronização inválidos.",
    duplicate: "Já existe.",
    invalid_input: "Dados inválidos.",
    invalid_bonus: "A cortesia vai de 0 a 100.000 ingressos.",
    event_closed: "Este evento está arquivado. Reabra o evento para criar lotes ou enviar ingressos.",
    mail_quota: "O envio de códigos por e-mail atingiu o limite de hoje. Entre com o Google ou tente de novo amanhã.",
    google_unavailable: "O login com Google está indisponível agora. Use o código por e-mail.",
    invalid_google_token: "Não conseguimos confirmar o login com o Google. Tente de novo.",
    google_email_unverified: "Sua conta Google não tem o e-mail confirmado. Use o código por e-mail.",
    google_account_mismatch: "Este e-mail já está ligado a outra conta Google. Entre com o código por e-mail.",
    account_suspended: "Sua conta está suspensa. Fale com o suporte para reativar.",
    confirmation_mismatch: "O e-mail digitado não confere com o da conta.",
    invalid_holder_name: "Nome muito longo (até 80 caracteres).",
    ticket_not_issued: "Esse número não está em um lote pago.",
    ticket_voided: "Esse ingresso está cancelado. Desfaça o cancelamento ou escolha outro número.",
    ticket_link_exists: "Esse ingresso já tem um link ativo. Copie o link da lista abaixo.",
    no_free_tickets: "Todos os ingressos pagos já estão com vendedores ou links. Crie um novo lote.",
    invalid_number: "Número inválido.",
    batch_not_refundable: "Só lotes pagos podem ser estornados.",
    payment_not_found: "Não achamos o pagamento na Stripe. Estorne por lá e registre aqui sem a Stripe.",
    invalid_reason: "Motivo muito longo (até 200 caracteres).",
    invalid_title: "Dê um título de até 120 caracteres.",
    invalid_body: "Texto muito longo (até 4.000 caracteres).",
    invalid_period: "Período inválido.",
    event_has_batches: "O evento tem lotes. Cancele os lotes não pagos antes; eventos com lotes pagos podem ser arquivados.",
  },
} as const;
