/**
 * Every user-facing text of the web app, in Brazilian Portuguese.
 *
 * Components never hard-code UI strings: they read them from here. There is no i18n framework on
 * purpose (national market only); centralizing keeps a future translation a mechanical change.
 */
export const texts = {
  meta: {
    title: "Ingresso Impresso",
    description:
      "Ingressos impressos, numerados e com QR code à prova de cópia, com check-in na porta pelo celular, mesmo sem internet.",
  },
  landing: {
    headline: "Ingressos impressos com QR code que não dá para copiar",
    lead: "Para bandas, festas de escola, igrejas e pequenos produtores que vendem ingresso na mão.",
    features: [
      "Arquivos prontos para imprimir em casa ou na gráfica",
      "Blocos numerados por vendedor e relatório de vendas",
      "Check-in pelo celular, funcionando sem internet",
    ],
    signIn: "Entrar",
  },
  common: {
    save: "Salvar",
    saving: "Salvando…",
    cancel: "Cancelar",
    remove: "Remover",
    loading: "Carregando…",
    add: "Adicionar",
    back: "Voltar",
    yes: "Sim",
    no: "Não",
    first: "Do nº",
    last: "Até o nº",
    range: (first: number, last: number) => `${String(first)} a ${String(last)}`,
  },
  login: {
    title: "Entrar",
    emailLabel: "Seu e-mail",
    emailPlaceholder: "voce@exemplo.com",
    sendCode: "Receber código",
    codeSentTo: (email: string) => `Enviamos um código de 6 dígitos para ${email}.`,
    codeLabel: "Código",
    verify: "Entrar",
    otherEmail: "Usar outro e-mail",
  },
  panel: {
    title: "Meus eventos",
    signOut: "Sair",
    newEvent: "Novo evento",
    empty: "Nenhum evento ainda. Crie o primeiro abaixo.",
    eventName: "Nome do evento",
    venue: "Local",
    startsAt: "Início",
    endsAt: "Fim",
    price: "Preço do ingresso (R$)",
    create: "Criar evento",
  },
  event: {
    tabs: {
      design: "Ingresso",
      batches: "Lotes",
      sellers: "Vendedores",
      voids: "Cancelamentos",
      files: "Arquivos",
      door: "Portaria",
      report: "Relatório",
    },
    design: {
      intro:
        "Monte o ingresso: envie a arte e posicione o número e o QR code. A prévia mostra uma folha A4 com ingressos de AMOSTRA.",
      art: "Arte (PNG ou JPEG)",
      artHint: (widthMm: number, heightMm: number) =>
        `A arte deve cobrir ${String(widthMm + 6)} × ${String(heightMm + 6)} mm (o ingresso + 3 mm de sangria em cada lado).`,
      artDpi: (dpi: number) => `Resolução da arte no tamanho final: ${String(dpi)} dpi.`,
      artLowDpi: "Abaixo de 300 dpi a impressão pode sair borrada.",
      noArt: "Sem arte (fundo liso)",
      removeArt: "Remover arte",
      size: "Tamanho do ingresso (sem canhoto)",
      width: "Largura (mm)",
      height: "Altura (mm)",
      background: "Cor de fundo",
      number: "Número",
      x: "Esquerda (mm)",
      y: "Topo (mm)",
      boxWidth: "Largura da caixa (mm)",
      boxHeight: "Altura da caixa (mm)",
      font: "Fonte",
      fonts: { display: "Bebas Neue (condensada)", mono: "Space Mono (monoespaçada)", sans: "Lato (simples)" },
      fontSize: "Tamanho (pt)",
      color: "Cor",
      align: "Alinhamento",
      aligns: { left: "Esquerda", center: "Centro", right: "Direita" },
      prefix: "Prefixo",
      digits: "Dígitos",
      qr: "QR code",
      qrSize: "Tamanho (mm, mínimo 22)",
      stub: "Canhoto",
      hasStub: "Com canhoto (fica com o vendedor)",
      stubSide: "Lado",
      sides: { left: "Esquerda", right: "Direita" },
      stubWidth: "Largura do canhoto (mm)",
      stubFields: "Campos do canhoto (um por linha; cada um pede cerca de 8 mm de altura do ingresso)",
      preview: "Pré-visualizar",
      previewing: "Gerando prévia…",
      saved: (version: number) => `Versão ${String(version)} salva.`,
      unsaved: "Ainda não salvo: os arquivos usam o ingresso padrão.",
    },
    batches: {
      intro:
        "Cada lote é uma faixa de números. Os ingressos de um lote só podem ser gerados depois do pagamento (por enquanto, confirmado manualmente).",
      quantity: "Quantidade",
      create: "Criar lote",
      empty: "Nenhum lote ainda.",
      status: {
        awaiting_payment: "Aguardando pagamento",
        paid: "Pago",
        canceled: "Cancelado",
      },
      markPaid: "Marcar como pago",
      cancelBatch: "Cancelar lote",
    },
    sellers: {
      intro: "Cadastre quem vende e entregue a cada um uma faixa de números.",
      name: "Nome",
      phone: "Telefone (opcional)",
      create: "Cadastrar vendedor",
      empty: "Nenhum vendedor ainda.",
      noRanges: "Sem faixa",
      assign: "Entregar faixa",
    },
    voids: {
      intro:
        "Cancele faixas devolvidas, perdidas ou que não devem entrar. Elas são bloqueadas na porta e não aparecem nos arquivos.",
      reason: "Motivo",
      reasons: { unsold: "Devolvido (não vendido)", lost: "Perdido ou roubado", revoked: "Outro motivo" },
      note: "Observação (opcional)",
      create: "Cancelar faixa",
      empty: "Nenhum cancelamento.",
      undo: "Desfazer",
      undone: "Desfeito",
    },
    files: {
      intro:
        "Gere os arquivos dos ingressos pagos. Ingressos cancelados não são incluídos. Cada arquivo leva alguns segundos (as imagens do WhatsApp, mais).",
      kind: "Arquivo",
      kinds: {
        home: "A4 para imprimir em casa",
        print: "PDF para gráfica (com sangria)",
        control: "Folha de controle por vendedor",
        whatsapp: "Imagens para WhatsApp (ZIP)",
      },
      scope: "Quais ingressos",
      scopeAll: "Todos os pagos",
      scopeBatch: (first: number, last: number) => `Lote ${String(first)}–${String(last)}`,
      scopeSeller: (name: string) => `Vendedor: ${name}`,
      cropMarks: "Marcas de corte (algumas gráficas preferem sem)",
      generate: "Gerar arquivo",
      empty: "Nenhum arquivo gerado ainda.",
      status: {
        queued: "Na fila",
        running: "Gerando…",
        done: "Pronto",
        failed: "Falhou",
      },
      tickets: (count: number) => `${String(count)} ingressos`,
      download: "Baixar",
      whatsappWarning: "Envie cada imagem a um só comprador: cópias são bloqueadas na porta.",
    },
    report: {
      intro:
        "Acerto por vendedor: ingressos pagos entregues, devoluções, perdas, vendidos declarados e o valor a acertar. Entradas e cópias vêm da portaria.",
      csv: "Baixar CSV",
      refresh: "Atualizar",
      generatedAt: (time: string) => `Atualizado às ${time}`,
      noPrice: "evento sem preço: o valor a acertar fica em branco",
      fileName: "relatorio-vendedores.csv",
      seller: "Vendedor",
      unassigned: "Sem vendedor",
      totals: "Total",
      amountDue: "A acertar",
      columns: {
        tickets: "Ingressos",
        unsold: "Devolvidos",
        lost: "Perdidos",
        revoked: "Outros cancel.",
        declaredSold: "Vendidos",
        entries: "Entradas",
        offlineDuplicates: "Duplicadas offline",
        blockedCopies: "Cópias barradas",
        voidEntries: "Entraram cancelados",
      },
      hints: {
        tickets: "Ingressos pagos entregues ao vendedor",
        unsold: "Cancelados como devolvidos sem vender",
        lost: "Cancelados como perdidos ou roubados",
        revoked: "Cancelados por outro motivo (contam como vendidos)",
        declaredSold: "Ingressos − devolvidos − perdidos",
        entries: "Ingressos que entraram",
        offlineDuplicates: "Cópias que entraram por celulares sem internet",
        blockedCopies: "Cópias barradas na porta",
        voidEntries: "Ingressos cancelados que entraram (o celular ainda não sabia do cancelamento)",
      },
      door: "Portaria",
      device: "Celular",
      noDevices: "Nenhum celular registrado.",
      rejected: (invalid: number, otherEvent: number) =>
        `QR falsos ou ilegíveis: ${String(invalid)} · ingressos de outro evento: ${String(otherEvent)}`,
      deviceColumns: {
        scans: "Leituras",
        firstEntries: "Entradas",
        offlineDuplicates: "Duplicadas offline",
        blockedCopies: "Cópias barradas",
        invalid: "Inválidos",
      },
    },
    door: {
      intro:
        "Crie um link para quem vai trabalhar na porta. Cada pessoa abre o link no celular, dá um nome ao aparelho e já pode ler os ingressos, mesmo sem internet.",
      entries: (count: number) => (count === 1 ? "1 ingresso já entrou." : `${String(count)} ingressos já entraram.`),
      label: "Para quem é o link",
      defaultLabel: "Equipe da porta",
      create: "Criar link",
      createdTitle: (label: string) => `Link criado: ${label}`,
      createdHint:
        "Copie ou compartilhe agora: o link não aparece de novo. Quem tiver o link consegue registrar um celular; se ele vazar, revogue e crie outro.",
      qrLabel: "QR code do link da portaria",
      copy: "Copiar link",
      copied: "Copiado!",
      whatsapp: "Enviar pelo WhatsApp",
      whatsappMessage: "Link da portaria (abra no celular que vai ler os ingressos):",
      hide: "Fechar",
      links: "Links",
      noLinks: "Nenhum link ainda.",
      activeUntil: (when: string) => `Ativo até ${when}`,
      expired: "Expirado",
      revoked: "Revogado",
      revokeLink: "Revogar link",
      devices: "Celulares",
      noDevices: "Nenhum celular registrado.",
      scans: (count: number) => (count === 1 ? "1 leitura" : `${String(count)} leituras`),
      lastSeen: (when: string) => `último contato ${when}`,
      neverSeen: "sem contato",
      disconnected: "desconectado",
      disconnect: "Desconectar",
    },
  },
  portaria: {
    title: "Portaria",
    loading: "Abrindo a portaria…",
    noAccess: "Abra o link de acesso que o organizador enviou para você.",
    registerTitle: "Registrar este celular",
    registerIntro: "Dê um nome a este celular. Ele aparece quando um ingresso já entrou por aqui.",
    deviceName: "Nome do celular",
    deviceNamePlaceholder: "Porta 1 - João",
    register: "Registrar",
    registering: "Registrando…",
    switchTitle: (deviceName: string) => `Este celular já está registrado como “${deviceName}”.`,
    keepDevice: "Continuar assim",
    useNewLink: "Usar o novo link",
    switchBlocked: "Há leituras não sincronizadas: conecte-se à internet e espere sincronizar antes de trocar de link.",
    revoked: "O acesso deste celular foi encerrado pelo organizador (ou o evento acabou).",
    forget: "Apagar os dados deste celular",
    forgetConfirm: "Apagar os dados da portaria deste celular?",
    start: "Começar a ler",
    stop: "Pausar",
    torchOn: "Acender lanterna",
    torchOff: "Apagar lanterna",
    entries: (count: number) => (count === 1 ? "1 entrada" : `${String(count)} entradas`),
    syncedAgo: (seconds: number) => (seconds < 5 ? "sincronizado agora" : `sincronizado há ${String(seconds)} s`),
    offlineFor: (minutes: number) => (minutes < 1 ? "sem sinal" : `sem sinal há ${String(minutes)} min`),
    neverSynced: "ainda não sincronizou",
    pending: (count: number) => (count === 1 ? "1 leitura não sincronizada" : `${String(count)} leituras não sincronizadas`),
    oneLineOffline: "Sem sinal: use um celular só por fila, senão cópias podem entrar por celulares diferentes.",
    checking: "Conferindo…",
    tapToContinue: "Toque para continuar",
    cameraError: "Não foi possível abrir a câmera. Libere o acesso à câmera nas configurações do navegador.",
    storageError: "Não foi possível salvar a leitura neste celular. Libere espaço e recarregue a página.",
    readiness: {
      title: "Pronto para ficar sem internet?",
      app: "App salvo para abrir sem internet",
      data: (time: string) => `Dados do evento atualizados às ${time}`,
      noData: "Dados do evento ainda não baixados",
      camera: "Câmera liberada",
      storage: "Armazenamento garantido",
      testScan: "Leitura de teste feita (leia qualquer QR, como o de um ingresso de amostra)",
      hint: "Abra este link no dia do evento, com internet, e deixe a tela aberta.",
    },
    result: {
      admit: "PODE ENTRAR",
      alreadyEntered: "JÁ ENTROU",
      alreadyEnteredAt: (time: string, device: string) => `às ${time} por ${device}`,
      voided: "INGRESSO CANCELADO",
      otherEvent: "INGRESSO DE OUTRO EVENTO",
      invalid: "INGRESSO INVÁLIDO",
      error: "ERRO NA LEITURA",
      voidReasons: { unsold: "devolvido sem vender", lost: "perdido ou roubado", revoked: "cancelado pelo organizador" },
      invalidReasons: {
        malformed: "QR ilegível ou que não é nosso",
        unknown_key: "assinatura desconhecida",
        revoked_key: "chave revogada",
        bad_signature: "falsificado",
      },
      seller: (name: string) => `Vendedor: ${name}`,
      number: (label: string) => `Nº ${label}`,
    },
  },
  errors: {
    generic: "Algo deu errado. Tente de novo.",
    network: "Sem conexão com o servidor. Verifique a internet e tente de novo.",
    unauthorized: "Sua sessão expirou. Entre de novo.",
    forbidden: "Você não tem permissão para isso.",
    not_found: "Não encontrado.",
    too_many_requests: "Muitas tentativas. Espere alguns minutos.",
    invalid_email: "E-mail inválido.",
    invalid_code: "Código errado ou expirado.",
    mail_unavailable: "Não conseguimos enviar o e-mail agora. Tente em alguns minutos.",
    invalid_name: "Nome inválido.",
    invalid_venue: "Local muito longo.",
    invalid_dates: "O fim precisa ser depois do início.",
    invalid_price: "Preço inválido.",
    invalid_design:
      "O ingresso tem medidas inválidas (veja o tamanho mínimo do QR, se tudo cabe no ingresso e se ele é alto o bastante para os campos do canhoto).",
    unsupported_art: "A arte precisa ser PNG ou JPEG.",
    art_too_large: "A arte é grande demais (máximo 10.000 px por lado).",
    payload_too_large: "Arquivo grande demais (máximo 20 MB).",
    unknown_art: "Arte não encontrada; envie de novo.",
    too_large_for_a4: "O ingresso (com canhoto) não cabe numa folha A4.",
    invalid_quantity: "Quantidade inválida (1 a 5.000).",
    batch_not_cancelable: "Só lotes não pagos podem ser cancelados.",
    batch_not_payable: "Este lote não está aguardando pagamento.",
    seller_exists: "Já existe um vendedor com esse nome.",
    invalid_phone: "Telefone muito longo.",
    invalid_range: "Faixa inválida.",
    range_not_issued: "Todos os números da faixa precisam estar em um lote.",
    range_overlap: "Essa faixa se sobrepõe a outra já entregue.",
    invalid_note: "Observação muito longa.",
    already_undone: "Esse cancelamento já foi desfeito.",
    invalid_scope: "Seleção inválida.",
    export_not_ready: "O arquivo ainda não está pronto.",
    export_expired: "O arquivo expirou. Gere de novo.",
    no_tickets: "Não há ingressos pagos e não cancelados nessa seleção.",
    too_many_tickets: "Ingressos demais num arquivo só (máximo 10.000).",
    invalid_label: "Nome do link inválido (1 a 60 caracteres).",
    invalid_device_name: "Dê um nome ao celular (até 40 caracteres).",
    too_many_devices: "Este link já registrou celulares demais. Crie outro link.",
    invalid_scans: "Leituras inválidas.",
    scan_conflict: "Leitura em conflito com outro celular.",
    invalid_cursor: "Dados de sincronização inválidos.",
    duplicate: "Já existe.",
    invalid_input: "Dados inválidos.",
  },
} as const;
